PRAGMA foreign_keys=OFF;--> statement-breakpoint
CREATE TABLE `__new_cricshort_ball_by_ball` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`BallID` text,
	`BallUniqueID` text,
	`ActualBallNo` text,
	`MatchID` text,
	`InningsNo` integer,
	`BattingTeamID` text,
	`TeamName` text,
	`StrikerID` text,
	`NonStrikerID` text,
	`BatsManName` text,
	`BowlerID` text,
	`BowlerName` text,
	`BowlerType` text,
	`OverNo` integer,
	`OverName` text,
	`BallNo` text,
	`Runs` text,
	`BallRuns` text,
	`RunsText` text,
	`ActualRuns` text,
	`IsOne` text,
	`IsTwo` text,
	`IsThree` text,
	`IsDotball` text,
	`Extras` text,
	`IsWide` text,
	`IsNoBall` text,
	`IsBye` text,
	`IsLegBye` text,
	`IsFour` text,
	`IsSix` text,
	`IsWicket` text,
	`WicketType` text,
	`Wickets` text,
	`VideoFile` text,
	`IsBowlerWicket` text,
	`CommentOver` text,
	`BallName` text,
	`CommentStrikers` text,
	`NewCommentry` text,
	`Commentry` text,
	`UPDCommentry` text,
	`Day` text,
	`SESSION_NO` text,
	`IsExtra` text,
	`OutBatsManID` text,
	`SNO` text,
	`Xpitch` text,
	`Ypitch` text,
	`RunRuns` text,
	`IsMaiden` text,
	`OverImage` text,
	`BowlTypeID` text,
	`BowlTypeName` text,
	`ShotTypeID` text,
	`ShotType` text,
	`IsBouncer` text,
	`IsFreeHit` text,
	`BallCount` text,
	`BCCheck` text,
	`TotalRuns` text,
	`TotalWickets` text,
	`BOWLING_LINE_ID` text,
	`BOWLING_LENGTH_ID` text,
	`FiveHaul` text,
	`HatCheck` text,
	`Flag` text,
	`FlagSet` text,
	`PenaltyRuns` text,
	`IsFifty` text,
	`IsHundred` text,
	`IsTwoHundred` text,
	`IsHattrick` text,
	FOREIGN KEY (`MatchID`) REFERENCES `cricshort_matches`(`MatchID`) ON UPDATE no action ON DELETE no action
);
--> statement-breakpoint
INSERT INTO `__new_cricshort_ball_by_ball`("id", "BallID", "BallUniqueID", "ActualBallNo", "MatchID", "InningsNo", "BattingTeamID", "TeamName", "StrikerID", "NonStrikerID", "BatsManName", "BowlerID", "BowlerName", "BowlerType", "OverNo", "OverName", "BallNo", "Runs", "BallRuns", "RunsText", "ActualRuns", "IsOne", "IsTwo", "IsThree", "IsDotball", "Extras", "IsWide", "IsNoBall", "IsBye", "IsLegBye", "IsFour", "IsSix", "IsWicket", "WicketType", "Wickets", "VideoFile", "IsBowlerWicket", "CommentOver", "BallName", "CommentStrikers", "NewCommentry", "Commentry", "UPDCommentry", "Day", "SESSION_NO", "IsExtra", "OutBatsManID", "SNO", "Xpitch", "Ypitch", "RunRuns", "IsMaiden", "OverImage", "BowlTypeID", "BowlTypeName", "ShotTypeID", "ShotType", "IsBouncer", "IsFreeHit", "BallCount", "BCCheck", "TotalRuns", "TotalWickets", "BOWLING_LINE_ID", "BOWLING_LENGTH_ID", "FiveHaul", "HatCheck", "Flag", "FlagSet", "PenaltyRuns", "IsFifty", "IsHundred", "IsTwoHundred", "IsHattrick") SELECT "id", "BallID", "BallUniqueID", "ActualBallNo", "MatchID", "InningsNo", "BattingTeamID", "TeamName", "StrikerID", "NonStrikerID", "BatsManName", "BowlerID", "BowlerName", "BowlerType", "OverNo", "OverName", "BallNo", "Runs", "BallRuns", "RunsText", "ActualRuns", "IsOne", "IsTwo", "IsThree", "IsDotball", "Extras", "IsWide", "IsNoBall", "IsBye", "IsLegBye", "IsFour", "IsSix", "IsWicket", "WicketType", "Wickets", "VideoFile", "IsBowlerWicket", "CommentOver", "BallName", "CommentStrikers", "NewCommentry", "Commentry", "UPDCommentry", "Day", "SESSION_NO", "IsExtra", "OutBatsManID", "SNO", "Xpitch", "Ypitch", "RunRuns", "IsMaiden", "OverImage", "BowlTypeID", "BowlTypeName", "ShotTypeID", "ShotType", "IsBouncer", "IsFreeHit", "BallCount", "BCCheck", "TotalRuns", "TotalWickets", "BOWLING_LINE_ID", "BOWLING_LENGTH_ID", "FiveHaul", "HatCheck", "Flag", "FlagSet", "PenaltyRuns", "IsFifty", "IsHundred", "IsTwoHundred", "IsHattrick" FROM `cricshort_ball_by_ball`;--> statement-breakpoint
DROP TABLE `cricshort_ball_by_ball`;--> statement-breakpoint
ALTER TABLE `__new_cricshort_ball_by_ball` RENAME TO `cricshort_ball_by_ball`;--> statement-breakpoint
PRAGMA foreign_keys=ON;--> statement-breakpoint
CREATE INDEX `ball_match_innings_team` ON `cricshort_ball_by_ball` (`MatchID`,`InningsNo`,`BattingTeamID`);