import { index, foreignKey } from "drizzle-orm/sqlite-core";
import { matches } from "./matches";
import { createTable } from "./tableCreator";

export const battingCard = createTable(
  "batting_card",
  (d) => ({
    id: d.integer({ mode: "number" }).primaryKey({ autoIncrement: true }),
    MatchID: d.integer({ mode: "number" }),
    InningsNo: d.integer({ mode: "number" }),
    TeamID: d.integer({ mode: "number" }),
    PlayerID: d.text(),
    PlayerName: d.text(),
    PlayerImage: d.text(),
    PlayingOrder: d.integer({ mode: "number" }),
    MatchPlayingOrder: d.integer({ mode: "number" }),
    BowlerName: d.text(),
    OutDesc: d.text(),
    ShortOutDesc: d.text(),
    Runs: d.integer({ mode: "number" }),
    Balls: d.integer({ mode: "number" }),
    DotBalls: d.integer({ mode: "number" }),
    DotBallPercentage: d.text(),
    DotBallFrequency: d.text(),
    Ones: d.integer({ mode: "number" }),
    Twos: d.integer({ mode: "number" }),
    Threes: d.integer({ mode: "number" }),
    Fours: d.integer({ mode: "number" }),
    Sixes: d.integer({ mode: "number" }),
    BoundaryPercentage: d.text(),
    BoundaryFrequency: d.text(),
    StrikeRate: d.text(),
    MinOver: d.integer({ mode: "number" }),
    MinStrikerOver: d.integer({ mode: "number" }),
    WicketNo: d.text(),
    AgainstFast: d.integer({ mode: "number" }),
    AgainstSpin: d.integer({ mode: "number" }),
    AgainstFastPercent: d.text(),
    AgainstSpinPercent: d.text(),
    PLAYER_ID: d.text(),
  }),
  (t) => [
    index("batting_match_innings_team").on(t.MatchID, t.InningsNo, t.TeamID),
    foreignKey({ columns: [t.MatchID], foreignColumns: [matches.MatchID] }),
  ],
);

export const bowlingCard = createTable(
  "bowling_card",
  (d) => ({
    id: d.integer({ mode: "number" }).primaryKey({ autoIncrement: true }),
    MatchID: d.integer({ mode: "number" }),
    InningsNo: d.integer({ mode: "number" }),
    TeamID: d.integer({ mode: "number" }),
    PlayerID: d.text(),
    PlayerName: d.text(),
    PlayerShortName: d.text(),
    PlayerImageName: d.text(),
    PlayerImage: d.text(),
    Overs: d.text(),
    Maidens: d.integer({ mode: "number" }),
    Runs: d.integer({ mode: "number" }),
    Wickets: d.integer({ mode: "number" }),
    Wides: d.integer({ mode: "number" }),
    NoBalls: d.integer({ mode: "number" }),
    Economy: d.text(),
    BowlingOrder: d.integer({ mode: "number" }),
    TotalLegalBallsBowled: d.integer({ mode: "number" }),
    ScoringBalls: d.integer({ mode: "number" }),
    DotBalls: d.integer({ mode: "number" }),
    DBPercent: d.text(),
    DBFrequency: d.text(),
    Ones: d.integer({ mode: "number" }),
    Twos: d.integer({ mode: "number" }),
    Threes: d.integer({ mode: "number" }),
    Fours: d.integer({ mode: "number" }),
    Sixes: d.integer({ mode: "number" }),
    BdryPercent: d.text(),
    BdryFreq: d.text(),
    StrikeRate: d.text(),
    FourPercent: d.text(),
    SixPercent: d.text(),
  }),
  (t) => [
    index("bowling_match_innings_team").on(t.MatchID, t.InningsNo, t.TeamID),
    foreignKey({ columns: [t.MatchID], foreignColumns: [matches.MatchID] }),
  ],
);

export const extras = createTable(
  "extras",
  (d) => ({
    id: d.integer({ mode: "number" }).primaryKey({ autoIncrement: true }),
    MatchID: d.text(),
    InningsNo: d.text(),
    TeamID: d.text(),
    Total: d.text(),
    TotalExtras: d.text(),
    Byes: d.text(),
    LegByes: d.text(),
    NoBalls: d.text(),
    Wides: d.text(),
    Penalty: d.text(),
    CurrentRunRate: d.text(),
    FallScore: d.text(),
    FallWickets: d.text(),
    FallOvers: d.text(),
    BattingTeamName: d.text(),
    BowlingTeamName: d.text(),
    MaxPartnerShipRuns: d.text(),
  }),
  (t) => [
    index("extras_match_innings_team").on(t.MatchID, t.InningsNo, t.TeamID),
    foreignKey({ columns: [t.MatchID], foreignColumns: [matches.MatchID] }),
  ],
);

export const partnershipScore = createTable(
  "partnership_score",
  (d) => ({
    id: d.integer({ mode: "number" }).primaryKey({ autoIncrement: true }),
    MatchID: d.text(),
    BattingTeamID: d.text(),
    InningsNo: d.text(),
    StrikerID: d.text(),
    Striker: d.text(),
    NonStrikerID: d.text(),
    NonStriker: d.text(),
    PartnershipTotal: d.text(),
    StrikerRuns: d.text(),
    StrikerBalls: d.text(),
    Extras: d.text(),
    NonStrikerRuns: d.text(),
    NonStrikerBalls: d.text(),
    MatchMaxOver: d.text(),
    MatchMinOver: d.text(),
    RowNumber: d.text(),
  }),
  (t) => [
    index("partnership_match_innings_team").on(
      t.MatchID,
      t.InningsNo,
      t.BattingTeamID,
    ),
    foreignKey({ columns: [t.MatchID], foreignColumns: [matches.MatchID] }),
  ],
);