import { index } from "drizzle-orm/sqlite-core";
import { createTable } from "./tableCreator";

export const matches = createTable(
  "matches",
  (d) => ({
    MatchID: d.integer({ mode: "number" }).primaryKey(),
    CompetitionID: d.integer({ mode: "number" }),
    MatchTypeID: d.integer({ mode: "number" }),
    MatchType: d.text(),
    MatchStatus: d.text(),
    MatchDate: d.text(),
    MatchDateNew: d.text(),
    MatchName: d.text(),
    MatchTime: d.text(),
    GMTMatchTime: d.text(),
    GMTMatchDate: d.text(),
    GMTMatchEndTime: d.text(),
    GMTMatchEndDate: d.text(),
    FirstBattingTeamID: d.integer({ mode: "number" }),
    FirstBattingTeamName: d.text(),
    SecondBattingTeamID: d.integer({ mode: "number" }),
    SecondBattingTeamName: d.text(),
    FirstBattingTeamCode: d.text(),
    SecondBattingTeamCode: d.text(),
    GroundID: d.integer({ mode: "number" }),
    GroundName: d.text(),
    Commentss: d.text(),
    TossTeam: d.text(),
    TossDetails: d.text(),
    TossText: d.text(),
    Flag: d.integer({ mode: "number" }),
    FirstBattingSummary: d.text(),
    SecondBattingSummary: d.text(),
    ClientMatchID: d.text(),
    MATCH_COMMENCE_START_DATE: d.text(),
    city: d.text(),
    FlickrAlbumID: d.text(),
    LiveStream: d.text(),
    FBURL: d.text(),
    T20ProMatchID: d.text(),
    Temperature: d.text(),
    WeatherIcon: d.text(),
    TempUpdatedDate: d.text(),
    GroundUmpire1ID: d.integer({ mode: "number" }),
    GroundUmpire2ID: d.integer({ mode: "number" }),
    GroundUmpire3ID: d.integer({ mode: "number" }),
    RefereeID: d.integer({ mode: "number" }),
    HomeTeamID: d.integer({ mode: "number" }),
    HomeTeamName: d.text(),
    HomeTeamColor1: d.text(),
    HomeTeamColor2: d.text(),
    AwayTeamColor1: d.text(),
    AwayTeamColor2: d.text(),
    AwayTeamID: d.integer({ mode: "number" }),
    AwayTeamName: d.text(),
    timezone1: d.text(),
    MatchEndDate: d.text(),
    MatchEndTime: d.text(),
    MATCH_NO_OF_OVERS: d.text(),
    ROUND_ID: d.text(),
    MatchTypeName: d.text(),
    RowNo: d.integer({ mode: "number" }),
    TeamType: d.text(),
    CompetitionName: d.text(),
    GroundUmpire1: d.text(),
    GroundUmpire2: d.text(),
    ThirdUmpire: d.text(),
    Comments: d.text(),
    HomeTeamLogo: d.text(),
    AwayTeamLogo: d.text(),
    MatchHomeTeamLogo: d.text(),
    MatchAwayTeamLogo: d.text(),
    VideoScorecard: d.integer({ mode: "number" }),
    TimeZone: d.text(),
    CurrentStrikerID: d.text(),
    CurrentStrikerName: d.text(),
    StrikerRuns: d.integer({ mode: "number" }),
    StrikerBalls: d.integer({ mode: "number" }),
    StrikerFours: d.integer({ mode: "number" }),
    StrikerSixes: d.integer({ mode: "number" }),
    StrikerSR: d.integer({ mode: "number" }),
    StrikerImage: d.text(),
    CurrentNonStrikerID: d.text(),
    CurrentNonStrikerName: d.text(),
    NonStrikerRuns: d.integer({ mode: "number" }),
    NonStrikerBalls: d.integer({ mode: "number" }),
    NonStrikerFours: d.integer({ mode: "number" }),
    NonStrikerSixes: d.integer({ mode: "number" }),
    NonStrikerSR: d.integer({ mode: "number" }),
    NonStrikerImage: d.text(),
    CurrentBowlerID: d.text(),
    CurrentBowlerName: d.text(),
    BowlerOvers: d.text(),
    BowlerRuns: d.integer({ mode: "number" }),
    BowlerMaidens: d.integer({ mode: "number" }),
    BowlerWickets: d.integer({ mode: "number" }),
    BowlerEconomy: d.integer({ mode: "number" }),
    BowlerSR: d.integer({ mode: "number" }),
    BowlerImage: d.text(),
    ChasingText: d.text(),
    MatchBreakComments: d.text(),
    MatchProgress: d.text(),
    CurrentInnings: d.text(),
    "1Summary": d.text(),
    "1FallScore": d.text(),
    "1FallWickets": d.text(),
    "1FallOvers": d.text(),
    "1RunRate": d.text(),
    "2Summary": d.text(),
    "2FallScore": d.text(),
    "2FallWickets": d.text(),
    "2FallOvers": d.text(),
    "2RunRate": d.text(),
    "3Summary": d.text(),
    "3FallScore": d.text(),
    "3FallWickets": d.text(),
    "3FallOvers": d.text(),
    "3RunRate": d.text(),
    "4Summary": d.text(),
    "4FallScore": d.text(),
    "4FallWickets": d.text(),
    "4FallOvers": d.text(),
    "4RunRate": d.text(),
    "5Summary": d.text(),
    "5FallScore": d.text(),
    "5FallWickets": d.text(),
    "5FallOvers": d.text(),
    "5RunRate": d.text(),
    "6Summary": d.text(),
    "6FallScore": d.text(),
    "6FallWickets": d.text(),
    "6FallOvers": d.text(),
    "6RunRate": d.text(),
    DivisionID: d.text(),
    SecondInningsFirstBattingID: d.integer({ mode: "number" }),
    SecondInningsFirstBattingName: d.text(),
    SecondInningsSecondBattingID: d.integer({ mode: "number" }),
    SecondInningsSecondBattingName: d.text(),
    ThirdInningsFirstBattingID: d.integer({ mode: "number" }),
    ThirdInningsFirstBattingName: d.text(),
    ThirdInningsSecondBattingID: d.integer({ mode: "number" }),
    ThirdInningsSecondBattingName: d.text(),
    WinningTeamID: d.integer({ mode: "number" }),
    MatchOrder: d.text(),
    RevisedOver: d.text(),
    RevisedTarget: d.text(),
    PreMatchCommentary: d.text(),
    PostMatchCommentary: d.text(),
    MatchRow: d.integer({ mode: "number" }),
    ProjectedScore: d.text(),
    "2ndProjectedScore": d.text(),
    "3rdProjectedScore": d.text(),
    MOM: d.text(),
    MOM_TYPE: d.text(),
    MOMPlayerId: d.text(),
    MOMRuns: d.text(),
    MOMBalls: d.text(),
    MOMWicket: d.text(),
    MOMRC: d.text(),
    MOMImage: d.text(),
    KO: d.text(),
  }),
  (t) => [index("MatchID_idx").on(t.MatchID)],
);