import { z } from "zod";

// {
//       "CompetitionID": 203,
//       "MatchID": 1847,
//       "MatchTypeID": 8,
//       "MatchType": "T20 (N)",
//       "MatchStatus": "Post",
//       "MatchDate": "2025-04-30",
//       "MatchDateNew": "30 Apr 2025",
//       "MatchName": "Chennai Super Kings vs Punjab Kings",
//       "MatchTime": "19:30",
//       "GMTMatchTime": "14:00 GMT",
//       "GMTMatchDate": "2025-04-30",
//       "GMTMatchEndTime": "18:29 GMT",
//       "GMTMatchEndDate": "2025-04-30",
//       "FirstBattingTeamID": 13,
//       "FirstBattingTeamName": "Chennai Super Kings",
//       "SecondBattingTeamID": 15,
//       "SecondBattingTeamName": "Punjab Kings",
//       "FirstBattingTeamCode": "CSK",
//       "SecondBattingTeamCode": "PBKS",
//       "GroundID": 18,
//       "GroundName": "MA Chidambaram Stadium",
//       "Commentss": "Punjab Kings Won by 4  Wickets ",
//       "TossTeam": "Punjab Kings",
//       "TossDetails": "Punjab Kings Won The Toss And Elected To Field",
//       "TossText": " Won The Toss And Elected To Field",
//       "Flag": 1,
//       "FirstBattingSummary": "190\/10 (19.2 Ov)",
//       "SecondBattingSummary": "194\/6 (19.4 Ov)",
//       "ClientMatchID": "",
//       "MATCH_COMMENCE_START_DATE": "2025-04-30 19:30:00",
//       "city": "Chennai",
//       "FlickrAlbumID": "",
//       "LiveStream": "",
//       "FBURL": "https:\/\/www.district.in\/events\/chennai-super-kings-team",
//       "T20ProMatchID": "",
//       "Temperature": "",
//       "WeatherIcon": "",
//       "TempUpdatedDate": "",
//       "GroundUmpire1ID": 526,
//       "GroundUmpire2ID": 603,
//       "GroundUmpire3ID": 261,
//       "RefereeID": 161,
//       "HomeTeamID": "13",
//       "HomeTeamName": "Chennai Super Kings",
//       "HomeTeamColor1": "#319490",
//       "HomeTeamColor2": "#df7317",
//       "AwayTeamColor1": "#319490",
//       "AwayTeamColor2": "#df7317",
//       "AwayTeamID": "15",
//       "AwayTeamName": "Punjab Kings",
//       "timezone1": "Asia\/Kolkata",
//       "MatchEndDate": "30 Apr 2025",
//       "MatchEndTime": "23:59",
//       "MATCH_NO_OF_OVERS": "20",
//       "ROUND_ID": "0",
//       "MatchTypeName": "T20",
//       "RowNo": 49,
//       "TeamType": null,
//       "CompetitionName": "Tata Ipl 2025",
//       "GroundUmpire1": "AKSHAY TOTRE",
//       "GroundUmpire2": "Anish Sahasrabudhe",
//       "ThirdUmpire": "Rohan Pandit",
//       "Comments": "Punjab Kings Won by 4  Wickets ",
//       "HomeTeamLogo": "https:\/\/scores.iplt20.com\/ipl\/teamlogos\/CSK.png",
//       "AwayTeamLogo": "https:\/\/scores.iplt20.com\/ipl\/teamlogos\/PBKS.png",
//       "MatchHomeTeamLogo": "https:\/\/scores.iplt20.com\/ipl\/teamlogos\/CSK.png",
//       "MatchAwayTeamLogo": "https:\/\/scores.iplt20.com\/ipl\/teamlogos\/PBKS.png",
//       "VideoScorecard": 0,
//       "TimeZone": "+9.5",
//       "CurrentStrikerID": "2021-100mb00000000586-8238f85f91de11",
//       "CurrentStrikerName": "Marco Jansen",
//       "StrikerRuns": 4,
//       "StrikerBalls": 2,
//       "StrikerFours": 1,
//       "StrikerSixes": 0,
//       "StrikerSR": 200,
//       "StrikerImage": "https:\/\/scores.iplt20.com\/ipl\/playerimages\/eGX5hl7xvl1742893520586.png",
//       "CurrentNonStrikerID": "2021-100mb00000000647-9259e0ee2fe911",
//       "CurrentNonStrikerName": "Josh Inglis",
//       "NonStrikerRuns": 6,
//       "NonStrikerBalls": 6,
//       "NonStrikerFours": 1,
//       "NonStrikerSixes": 0,
//       "NonStrikerSR": 100,
//       "NonStrikerImage": "https:\/\/scores.iplt20.com\/ipl\/playerimages\/pF5Tf7QBjx1742893533647.png",
//       "CurrentBowlerID": "2018-100mb00000000008-787fc4ece99b11",
//       "CurrentBowlerName": "Khaleel Ahmed",
//       "BowlerOvers": "3.4",
//       "BowlerRuns": 28,
//       "BowlerMaidens": 0,
//       "BowlerWickets": 2,
//       "BowlerEconomy": 7.64,
//       "BowlerSR": 11,
//       "BowlerImage": "https:\/\/scores.iplt20.com\/ipl\/playerimages\/mSQ4IYyuPH17422228478.png",
//       "ChasingText": "",
//       "MatchBreakComments": "",
//       "MatchProgress": "",
//       "CurrentInnings": "2",
//       "1Summary": "190\/10 (19.2 Overs)",
//       "1FallScore": "190",
//       "1FallWickets": "10",
//       "1FallOvers": "19.2",
//       "1RunRate": "9.83",
//       "2Summary": "194\/6 (19.4 Overs)",
//       "2FallScore": "194",
//       "2FallWickets": "6",
//       "2FallOvers": "19.4",
//       "2RunRate": "9.86",
//       "3Summary": "",
//       "3FallScore": "",
//       "3FallWickets": "",
//       "3FallOvers": "",
//       "3RunRate": "",
//       "4Summary": "",
//       "4FallScore": "",
//       "4FallWickets": "",
//       "4FallOvers": "",
//       "4RunRate": "",
//       "5Summary": "",
//       "5FallScore": "",
//       "5FallWickets": "",
//       "5FallOvers": "",
//       "5RunRate": "",
//       "6Summary": "",
//       "6FallScore": "",
//       "6FallWickets": "",
//       "6FallOvers": "",
//       "6RunRate": "",
//       "DivisionID": "6",
//       "SecondInningsFirstBattingID": null,
//       "SecondInningsFirstBattingName": "",
//       "SecondInningsSecondBattingID": null,
//       "SecondInningsSecondBattingName": "",
//       "ThirdInningsFirstBattingID": null,
//       "ThirdInningsFirstBattingName": "",
//       "ThirdInningsSecondBattingID": null,
//       "ThirdInningsSecondBattingName": "",
//       "WinningTeamID": "15",
//       "MatchOrder": "Match 49",
//       "RevisedOver": "",
//       "RevisedTarget": "",
//       "PreMatchCommentary": "<p>Hello and welcome to the LIVE action of Match 49 in the TATA IPL 2025 &ndash; it&#39;s a royal showdown between <strong><span style=\"color:#f1c40f\">Chennai Super Kings<\/span>&nbsp;<img alt=\"\" src=\"https:\/\/bcci-stats-sports-mechanic.s3.amazonaws.com\/matchcentre\/images\/commentary\/smiley\/CSK-text.png\" style=\"height:20px; width:43px\" title=\"\" \/><\/strong> and <span style=\"color:#c0392b\"><strong>Punjab Kings&nbsp;<img alt=\"\" src=\"https:\/\/bcci-stats-sports-mechanic.s3.amazonaws.com\/matchcentre\/images\/commentary\/smiley\/PK-text.png\" style=\"height:20px; width:54px\" title=\"\" \/><\/strong><\/span> at the Anbuden. It&#39;s do-or-die for<strong> <\/strong>MS Dhoni&rsquo;s Men in Yellow &ndash; a loss tonight will seal their fate and knock them out of playoff contention. On the other hand, Punjab Kings, led by the ever-calm Shreyas Iyer, are sitting on 5 wins from 9 games. A win today could push them firmly into the top-four conversation.<\/p>\n\n<p>&nbsp;<\/p>\n\n<p>Punjab had the upper hand in the previous encounter between these two sides earlier this season, but with CSK playing at home &ndash; and their pride on the line &ndash; expect nothing short of a fierce contest.<\/p>\n\n<p>&nbsp;<\/p>\n\n<p>Will the Super Kings roar back and keep their hopes alive? Or will the Kings from the North deliver another body blow?<\/p>\n\n<p><img alt=\"\" src=\"https:\/\/scores.bcci.tv\/matchcentre\/commentaryFiles\/IPL 2025 Head to Head - 640px width (3)_1746020452.jpg\" \/><\/p>\n\n<p><strong>VENUE STATS:<\/strong><\/p>\n\n<p>Teams have preferred to chase here at the venue, with the captains opting to field first in 4\/5 games played here so far this season and the chasing teams winning 3 of the 5 games. 158 is the Avg score, with spinners getting 48% of the wickets alongside 52% of the pacers&#39; wickets. Is it Spin to win in Chepauk again tonight?<\/p>\n\n<p>&nbsp;<\/p>\n\n<p><strong>PITCH REPORT | Graeme Swann and Aaron Finch:<\/strong><\/p>\n\n<p>&quot;It is a 68 meter boundary on one side, and 65 meters on the other, the straight boundary is 80 meters. This wicket had been used already, and the KKR spinners wreaked havoc in that game.&nbsp;There&#39;s not a blade of grass on the pitch, and it&#39;s very, very dry.&nbsp;As the new ball starts to wear off, it&#39;s going to spin. As a batter, you&#39;ve got to make the majority of runs when the ball is harder and skidding on.&quot;<\/p>\n\n<p><img alt=\"\" src=\"https:\/\/scores.bcci.tv\/matchcentre\/commentaryFiles\/IPl Stats Temp 2024 - 2025-04-30T185935_1746020489.jpg\" \/><\/p>\n\n<p><strong>TOSS:<\/strong><\/p>\n\n<p><span style=\"color:#c0392b\"><strong>Shreyas Iyer calls it right and Punjab Kings <img alt=\"\" src=\"https:\/\/bcci-stats-sports-mechanic.s3.amazonaws.com\/matchcentre\/images\/commentary\/smiley\/PK-text.png\" style=\"height:20px; width:54px\" title=\"\" \/>&nbsp;will field first!<\/strong><\/span><\/p>\n\n<blockquote class=\"twitter-tweet\"><p lang=\"en\" dir=\"ltr\">???? Toss ????<a href=\"https:\/\/twitter.com\/PunjabKingsIPL?ref_src=twsrc%5Etfw\">@PunjabKingsIPL<\/a> won the toss and elected to field against <a href=\"https:\/\/twitter.com\/ChennaiIPL?ref_src=twsrc%5Etfw\">@ChennaiIPL<\/a> <br><br>Updates ?? <a href=\"https:\/\/t.co\/eXWTTv7Xhd\">https:\/\/t.co\/eXWTTv7Xhd<\/a> <a href=\"https:\/\/twitter.com\/hashtag\/TATAIPL?src=hash&amp;ref_src=twsrc%5Etfw\">#TATAIPL<\/a> | <a href=\"https:\/\/twitter.com\/hashtag\/CSKvPBKS?src=hash&amp;ref_src=twsrc%5Etfw\">#CSKvPBKS<\/a> <a href=\"https:\/\/t.co\/xFdgaB2zOx\">pic.twitter.com\/xFdgaB2zOx<\/a><\/p>&mdash; IndianPremierLeague (@IPL) <a href=\"https:\/\/twitter.com\/IPL\/status\/1917573864327950400?ref_src=twsrc%5Etfw\">April 30, 2025<\/a><\/blockquote> <script async src=\"https:\/\/platform.twitter.com\/widgets.js\" charset=\"utf-8\"><\/script>",
//       "PostMatchCommentary": "<p><strong>Powerplay (Overs 1-6)<br \/>\n<span style=\"color:#f39c12\">CSK:- 48\/3 (8 rpo, 7x4, 1x6) <\/span>||<span style=\"color:#f39c12\"> <\/span><span style=\"color:#c0392b\">PBKS:- 51\/1 (8.5 rpo, 8x4, 1x6)<\/span><br \/>\n<br \/>\nMiddle Overs (Overs 7-15)<br \/>\n<span style=\"color:#f39c12\">CSK:- 86\/1 (9.55 rpo, 8x4, 2x6)&nbsp;<\/span>||<span style=\"color:#f39c12\"> <\/span><span style=\"color:#c0392b\">PBKS:- 88\/2 (9.77 rpo, 7x4, 4x6)<\/span><br \/>\n<br \/>\nDeath Overs (Overs 16-20)<br \/>\n<span style=\"color:#f39c12\">CSK:- 56\/6 (12.9 rpo, 4x4, 4x6)&nbsp;<\/span>||<span style=\"color:#f39c12\"> <\/span><span style=\"color:#c0392b\">PBKS:- 55\/3 (11 rpo, 4x4, 4x6)<\/span><\/strong><\/p>\n\n<p>&nbsp;<\/p>\n\n<p>Punjab Kings edged out Chennai Super Kings by 4 wickets in a high-octane clash at Chepauk, successfully chasing 191 with two balls to spare and to <span style=\"color:#c0392b\"><strong>move to the 2nd spot on the points table<\/strong><\/span>. After being put in to bat first, the Men in Yellow had lost three wickets inside the Powerplay after which <span style=\"color:#f39c12\"><strong>Sam Curran&rsquo;s explosive 88 off 47 lit up CSK&rsquo;s innings<\/strong><\/span>, but a collapse post his dismissal in the end, highlighted by <span style=\"color:#c0392b\"><strong>Yuzvendra Chahal&#39;s 2nd Hat-Trick in the IPL<\/strong><\/span>, saw Punjab Kings stage a comeback and restrict CSK to 190 in 19.2 overs.<\/p>\n\n<p>&nbsp;<\/p>\n\n<p>In the chase, Punjab Kings made the most of the Powerplay and Priyansh Arya got them off to a flyer, cracking five boundaries in his quick 23 and further Prabhsimran Singh anchored the innings with a composed 54 off 36 balls alongside<span style=\"color:#c0392b\"><strong> skipper Shreyas Iyer whose fighting 72 off 41 balls<\/strong><\/span>, ensured the asking rate never spiraled out of control.&nbsp;Despite a few stumbles late on, Shashank Singh, Inglis and Jansen held their nerve to seal the win, helping the<span style=\"color:#c0392b\"><strong> Kings in the North do the double over the Super Kings.<\/strong><\/span> And officially, <strong>Chennai Super Kings are out of contention for this year&#39;s IPL, and for the first time in their franchise history, they will miss out on the playoffs for consecutive years!<\/strong><\/p>\n\n<p>&nbsp;<\/p>\n\n<p><span style=\"color:#f39c12\"><strong>MS Dhoni, CSK Captain:<\/strong><\/span> &quot;We finally put up a decent total, but I still feel we were 15 runs short. The partnership between Brevis and Sam was excellent and turned the game, but our dropped catches didn&rsquo;t help. Losing four wickets in the penultimate over and not playing the last four balls really hurt us. Sam&rsquo;s a fighter, and today&rsquo;s pitch suited him better. Brevis brings momentum, energy, and power&mdash;he&rsquo;s shaping up to be a real asset.&quot;<\/p>\n\n<p>&nbsp;<\/p>\n\n<p><span style=\"color:#c0392b\"><strong>Shreyas Iyer is the Player of the Match<\/strong><\/span><\/p>\n\n<p><span style=\"color:#c0392b\"><strong>Shreyas Iyer, Punjab Kings Captain &amp; Player of Match:<\/strong><\/span> &quot;I love chasing and taking charge when there&rsquo;s a big total. I&rsquo;ve been putting in a lot of work in the nets, especially against the new ball, and that&rsquo;s boosted my confidence. I focus on staying present and reacting to the ball, no matter where I&rsquo;m playing. During the chase, we didn&rsquo;t want to leave it late against their strong death bowlers, so the plan was to go hard early and back our power-hitters. Prabh and Priyansh were smart and played really well, not just slogging but applying themselves.&quot;<\/p>\n",
//       "MatchRow": 49,
//       "ProjectedScore": "197",
//       "2ndProjectedScore": "0",
//       "3rdProjectedScore": "0",
//       "MOM": "Shreyas Iyer",
//       "MOM_TYPE": "Batting",
//       "MOMPlayerId": "12",
//       "MOMRuns": "72",
//       "MOMBalls": "41",
//       "MOMWicket": "-",
//       "MOMRC": "-",
//       "MOMImage": "https:\/\/scores.iplt20.com\/ipl\/playerimages\/oIJxFMSV5z174289324712.png",
//       "KO": ""
//     },

export const matchSchema = z.object({
  MatchID: z.number(),
  CompetitionID: z.number().nullable(),
  MatchTypeID: z.number().nullable(),
  MatchType: z.string().nullable(),
  MatchStatus: z.string().nullable(),
  MatchDate: z.string().nullable(),
  MatchDateNew: z.string().nullable(),
  MatchName: z.string().nullable(),
  MatchTime: z.string().nullable(),
  HomeTeamID: z.string().nullable(),
  HomeTeamName: z.string().nullable(),
  HomeTeamLogo: z.string().nullable(),
  AwayTeamID: z.string().nullable(),
  AwayTeamName: z.string().nullable(),
  AwayTeamLogo: z.string().nullable(),
  GroundName: z.string().nullable(),
  city: z.string().nullable(),
  Comments: z.string().nullable(),
  FirstBattingSummary: z.string().nullable(),
  SecondInningsFirstBattingID: z.string().nullable(),
  SecondInningsSecondBattingID: z.string().nullable(),
  WinningTeamID: z.string().nullable(),
  MatchOrder: z.string().nullable(),
});

export const matchesSchema = z.object({
  Matchsummary: z.array(matchSchema),
});

export type Match = z.infer<typeof matchSchema>;
export type Matches = z.infer<typeof matchesSchema>;
